### PR TITLE
Suggestion for improved behaviour mid-sized windows

### PR DESCRIPTION
**Pull request by hamishwillee**
This is a very useful plugin, but the right-overlay approach makes it a pain to use for people who work in reduced size (but not mobile size) windows - because the content gets swamped:
image

What this does is add a circular toggle that turns the menu on and off on hover. That means you only have the menu when you want it. 
image

See it here: https://docs.px4.io/v1.testing/en/advanced_config/parameter_reference.html

I changed quite a lot of other things - I quite like meaningful names for things - and right-anchor in no way reflects what this plugin does :-).  

Anyway, consider this "suggestion for improved design of menu". The PR is not mergable as is, but I hope we can have a discussion :)

### CODE REVIEW

**Comment by xuek9900** [comment]
Your opinion is great, and to be honest, I noticed it.

I will merge your code and optimize it before releasing it. Because of work, it may be a little later. Sorry.

Finally, thank you for your contribution.

**Comment by xuek9900** [comment]
> I changed quite a lot of other things - I quite like meaningful names for things - and right-anchor in no way reflects what this plugin does :-).

> Anyway, consider this "suggestion for improved design of menu". The PR is not mergable as is, but I hope we can have a discussion :)

I very much agree with this point. It was my initial design that was not good. However, the name of this plug-in has been fixed in "right-anchor". Therefore, I should still take it into account when optimizing, rather than abandon it completely, at least for the sake of user perception.

If I'm going to ignore all this, unless I release a new plug-in and start from scratch.

As a result, naming conventions may not be exactly what you want. i 'm sorry.

**Comment by xuek9900** [comment]
'0.4.2' published.

Added 'expand' config.

**Comment by hamishwillee** [comment]
Hi @xuekai-china 

Really appreciate you taking the time to include the menu collapse into the plugin - now I don't have to branch :-). I also like that you added option to toggle on click (many people prefer that). I was also considering limiting the width of the menu because at some widths it can be hard to click outside the area - another good reason why some people like the click toggle.

> As a result, naming conventions may not be exactly what you want. i 'm sorry.

Don't worry about that. You have an obligation to existing users not to break their code or expectations - I respect that!

Keep up the excellent work.

**Pull request merged**
